package model.services;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.services.common.AppModule;

import model.view.MnjWarrantyDataLoaderVOImpl;
import model.view.MnjWarrantyManagementHeaderVOExSetParentImpl;
import model.view.MnjWarrantyManagementHeaderVOImpl;
import model.view.MnjWarrantyManagementLineVOImpl;
import model.view.WarrHeaderScheduleHistoryVOImpl;
import model.view.WarrantyGRNVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 26 14:40:03 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    /**
     * Method to set page parameter value 
     * */

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {

        System.out.println("Session UserId: " + userId);
        
        System.out.println("Session RespId: " + respId);

        


        if (userId != null) {
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
            userSession.setAttribute("userId", userId);
             
    //            userSession.setAttribute("orgId", orgId);
            userSession.setAttribute("respId", respId);
    
            
            
       
        }
    }

    /**
     * Container's getter for MnjWarrantyManagementHeaderVO1.
     * @return MnjWarrantyManagementHeaderVO1
     */
    public ViewObjectImpl getMnjWarrantyManagementHeaderVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementHeaderVO1");
    }

    /**
     * Container's getter for MnjWarrantyManagementLineVO1.
     * @return MnjWarrantyManagementLineVO1
     */
    public ViewObjectImpl getMnjWarrantyManagementLineVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementLineVO1");
    }

    /**
     * Container's getter for MnjWarrantyReplaceHeaderVO1.
     * @return MnjWarrantyReplaceHeaderVO1
     */
    public ViewObjectImpl getMnjWarrantyReplaceHeaderVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyReplaceHeaderVO1");
    }

    /**
     * Container's getter for MnjWarrantyReplaceLineVO1.
     * @return MnjWarrantyReplaceLineVO1
     */
    public ViewObjectImpl getMnjWarrantyReplaceLineVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyReplaceLineVO1");
    }

    /**
     * Container's getter for WarrantyGRNVO1.
     * @return WarrantyGRNVO1
     */
    public ViewObjectImpl getWarrantyGRNVO1() {
        return (ViewObjectImpl)findViewObject("WarrantyGRNVO1");
    }

    /**
     * Container's getter for MnjWarrantyManagementLiFkLink1.
     * @return MnjWarrantyManagementLiFkLink1
     */
    public ViewLinkImpl getMnjWarrantyManagementLiFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjWarrantyManagementLiFkLink1");
    }

    /**
     * Container's getter for MnjWarrantyReplaceHeaderr01Link1.
     * @return MnjWarrantyReplaceHeaderr01Link1
     */
    public ViewLinkImpl getMnjWarrantyReplaceHeaderr01Link1() {
        return (ViewLinkImpl)findViewLink("MnjWarrantyReplaceHeaderr01Link1");
    }

    /**
     * Container's getter for MnjWarrantyReplaceLineR01Link1.
     * @return MnjWarrantyReplaceLineR01Link1
     */
    public ViewLinkImpl getMnjWarrantyReplaceLineR01Link1() {
        return (ViewLinkImpl)findViewLink("MnjWarrantyReplaceLineR01Link1");
    }

    /**
     * Container's getter for MnjWarrantyDataLoaderVO1.
     * @return MnjWarrantyDataLoaderVO1
     */
    public ViewObjectImpl getMnjWarrantyDataLoaderVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyDataLoaderVO1");
    }


    /**
     * Container's getter for MnjWarrantyManagementHeaderVOEx1.
     * @return MnjWarrantyManagementHeaderVOEx1
     */
    public ViewObjectImpl getMnjWarrantyManagementHeaderVOEx1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementHeaderVOEx1");
    }

    /**
     * Container's getter for MnjWarrantyManagementHeaderVOExSetParent1.
     * @return MnjWarrantyManagementHeaderVOExSetParent1
     */
    public ViewObjectImpl getMnjWarrantyManagementHeaderVOExSetParent1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementHeaderVOExSetParent1");
    }

    /**
     * Container's getter for MnjWarrDataLoaderSetParVO1.
     * @return MnjWarrDataLoaderSetParVO1
     */
    public ViewObjectImpl getMnjWarrDataLoaderSetParVO1() {
        return (ViewObjectImpl)findViewObject("MnjWarrDataLoaderSetParVO1");
    }

    /**
     * Container's getter for MnjWarrantyManagementLineVOEx1.
     * @return MnjWarrantyManagementLineVOEx1
     */
    public ViewObjectImpl getMnjWarrantyManagementLineVOEx1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementLineVOEx1");
    }

    /**
     * Container's getter for MnjWarrantyManagementHeaderVOEx2_1.
     * @return MnjWarrantyManagementHeaderVOEx2_1
     */
    public ViewObjectImpl getMnjWarrantyManagementHeaderVOEx2_1() {
        return (ViewObjectImpl)findViewObject("MnjWarrantyManagementHeaderVOEx2_1");
    }

    /**
     * Container's getter for WarrHeaderScheduleHistoryVO1.
     * @return WarrHeaderScheduleHistoryVO1
     */
    public CustomViewImpl getWarrHeaderScheduleHistoryVO1() {
        return (CustomViewImpl)findViewObject("WarrHeaderScheduleHistoryVO1");
    }

    /**
     * Container's getter for MnjWarrHeaderVO_vs_WarrHeaderScheduleHistoryVO_VL1.
     * @return MnjWarrHeaderVO_vs_WarrHeaderScheduleHistoryVO_VL1
     */
    public ViewLinkImpl getMnjWarrHeaderVO_vs_WarrHeaderScheduleHistoryVO_VL1() {
        return (ViewLinkImpl)findViewLink("MnjWarrHeaderVO_vs_WarrHeaderScheduleHistoryVO_VL1");
    }

    /**
     * Container's getter for WarrLineScheduleHistoryVO1.
     * @return WarrLineScheduleHistoryVO1
     */
    public CustomViewImpl getWarrLineScheduleHistoryVO1() {
        return (CustomViewImpl)findViewObject("WarrLineScheduleHistoryVO1");
    }

    /**
     * Container's getter for MnjWarrHeaderVO_vs_WarrLineScheduleHistory_VL1.
     * @return MnjWarrHeaderVO_vs_WarrLineScheduleHistory_VL1
     */
    public ViewLinkImpl getMnjWarrHeaderVO_vs_WarrLineScheduleHistory_VL1() {
        return (ViewLinkImpl)findViewLink("MnjWarrHeaderVO_vs_WarrLineScheduleHistory_VL1");
    }
}
