package model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 26 15:03:17 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjWarrantyReplaceLineEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getDetailId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        Organization {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getOrganization();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setOrganization((String)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Department {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getDepartment();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        ItemName {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getItemName();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setItemName((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        Qty {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getQty();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setQty((Number)value);
            }
        }
        ,
        VersionNo {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        RespId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getRespId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setRespId((Number)value);
            }
        }
        ,
        UserId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getUserId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setUserId((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        WarrantyStartDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyStartDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyStartDate((Date)value);
            }
        }
        ,
        WarrantyEndDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyEndDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyEndDate((Date)value);
            }
        }
        ,
        WarrantyCard {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyCard();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyCard((String)value);
            }
        }
        ,
        Invoice {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getInvoice();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setInvoice((String)value);
            }
        }
        ,
        PurchaseDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPurchaseDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPurchaseDate((Date)value);
            }
        }
        ,
        PurchasePrice {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPurchasePrice();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPurchasePrice((Number)value);
            }
        }
        ,
        SupplierName {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getSupplierName();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setSupplierName((String)value);
            }
        }
        ,
        TotalAmount {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getTotalAmount();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setTotalAmount((Number)value);
            }
        }
        ,
        BrandName {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getBrandName();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setBrandName((String)value);
            }
        }
        ,
        WarrantyMonths {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyMonths();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyMonths((Number)value);
            }
        }
        ,
        PrefixItem {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPrefixItem();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPrefixItem((String)value);
            }
        }
        ,
        FixedAssetTagId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getFixedAssetTagId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setFixedAssetTagId((String)value);
            }
        }
        ,
        Grn {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getGrn();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setGrn((Number)value);
            }
        }
        ,
        Pr {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPr();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPr((Number)value);
            }
        }
        ,
        Spo {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getSpo();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setSpo((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getItemId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        ProductSerialNo {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getProductSerialNo();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setProductSerialNo((String)value);
            }
        }
        ,
        ProductId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getProductId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setProductId((String)value);
            }
        }
        ,
        GrnDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getGrnDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setGrnDate((Date)value);
            }
        }
        ,
        WarrantyId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyId((String)value);
            }
        }
        ,
        Unit {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getUnit();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setUnit((String)value);
            }
        }
        ,
        BillNo {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getBillNo();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setBillNo((String)value);
            }
        }
        ,
        Uom {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getUom();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        BillDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getBillDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setBillDate((Date)value);
            }
        }
        ,
        ProductUser {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getProductUser();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setProductUser((String)value);
            }
        }
        ,
        WarrantyRemainingDays {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyRemainingDays();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyRemainingDays((Date)value);
            }
        }
        ,
        ReplacementDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getReplacementDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setReplacementDate((Date)value);
            }
        }
        ,
        Location {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getLocation();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setLocation((String)value);
            }
        }
        ,
        VendorId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getVendorId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setVendorId((Number)value);
            }
        }
        ,
        PoLineId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPoLineId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPoLineId((Number)value);
            }
        }
        ,
        PoHeaderId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getPoHeaderId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setPoHeaderId((Number)value);
            }
        }
        ,
        WarrantyTag {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getWarrantyTag();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setWarrantyTag((String)value);
            }
        }
        ,
        ProductUserDept {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getProductUserDept();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setProductUserDept((String)value);
            }
        }
        ,
        ProductUserEmpId {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getProductUserEmpId();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setProductUserEmpId((Number)value);
            }
        }
        ,
        CostCenter {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getCostCenter();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setCostCenter((Number)value);
            }
        }
        ,
        CostCenterName {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getCostCenterName();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setCostCenterName((String)value);
            }
        }
        ,
        LastMaintainDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getLastMaintainDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setLastMaintainDate((Date)value);
            }
        }
        ,
        MaintainPeriod {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getMaintainPeriod();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setMaintainPeriod((Number)value);
            }
        }
        ,
        NextMaintainDate {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getNextMaintainDate();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setNextMaintainDate((Date)value);
            }
        }
        ,
        ScheduleMaintainFlag {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getScheduleMaintainFlag();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setScheduleMaintainFlag((String)value);
            }
        }
        ,
        MnjWarrantyManagementLineEO {
            public Object get(MnjWarrantyReplaceLineEOImpl obj) {
                return obj.getMnjWarrantyManagementLineEO();
            }

            public void put(MnjWarrantyReplaceLineEOImpl obj, Object value) {
                obj.setMnjWarrantyManagementLineEO((MnjWarrantyManagementLineEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjWarrantyReplaceLineEOImpl object);

        public abstract void put(MnjWarrantyReplaceLineEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ORGANIZATION = AttributesEnum.Organization.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int ITEMNAME = AttributesEnum.ItemName.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int WARRANTYSTARTDATE = AttributesEnum.WarrantyStartDate.index();
    public static final int WARRANTYENDDATE = AttributesEnum.WarrantyEndDate.index();
    public static final int WARRANTYCARD = AttributesEnum.WarrantyCard.index();
    public static final int INVOICE = AttributesEnum.Invoice.index();
    public static final int PURCHASEDATE = AttributesEnum.PurchaseDate.index();
    public static final int PURCHASEPRICE = AttributesEnum.PurchasePrice.index();
    public static final int SUPPLIERNAME = AttributesEnum.SupplierName.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int BRANDNAME = AttributesEnum.BrandName.index();
    public static final int WARRANTYMONTHS = AttributesEnum.WarrantyMonths.index();
    public static final int PREFIXITEM = AttributesEnum.PrefixItem.index();
    public static final int FIXEDASSETTAGID = AttributesEnum.FixedAssetTagId.index();
    public static final int GRN = AttributesEnum.Grn.index();
    public static final int PR = AttributesEnum.Pr.index();
    public static final int SPO = AttributesEnum.Spo.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int PRODUCTSERIALNO = AttributesEnum.ProductSerialNo.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int GRNDATE = AttributesEnum.GrnDate.index();
    public static final int WARRANTYID = AttributesEnum.WarrantyId.index();
    public static final int UNIT = AttributesEnum.Unit.index();
    public static final int BILLNO = AttributesEnum.BillNo.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int BILLDATE = AttributesEnum.BillDate.index();
    public static final int PRODUCTUSER = AttributesEnum.ProductUser.index();
    public static final int WARRANTYREMAININGDAYS = AttributesEnum.WarrantyRemainingDays.index();
    public static final int REPLACEMENTDATE = AttributesEnum.ReplacementDate.index();
    public static final int LOCATION = AttributesEnum.Location.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int POLINEID = AttributesEnum.PoLineId.index();
    public static final int POHEADERID = AttributesEnum.PoHeaderId.index();
    public static final int WARRANTYTAG = AttributesEnum.WarrantyTag.index();
    public static final int PRODUCTUSERDEPT = AttributesEnum.ProductUserDept.index();
    public static final int PRODUCTUSEREMPID = AttributesEnum.ProductUserEmpId.index();
    public static final int COSTCENTER = AttributesEnum.CostCenter.index();
    public static final int COSTCENTERNAME = AttributesEnum.CostCenterName.index();
    public static final int LASTMAINTAINDATE = AttributesEnum.LastMaintainDate.index();
    public static final int MAINTAINPERIOD = AttributesEnum.MaintainPeriod.index();
    public static final int NEXTMAINTAINDATE = AttributesEnum.NextMaintainDate.index();
    public static final int SCHEDULEMAINTAINFLAG = AttributesEnum.ScheduleMaintainFlag.index();
    public static final int MNJWARRANTYMANAGEMENTLINEEO = AttributesEnum.MnjWarrantyManagementLineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjWarrantyReplaceLineEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.MnjWarrantyReplaceLineEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for Organization, using the alias name Organization.
     * @return the Organization
     */
    public String getOrganization() {
        return (String)getAttributeInternal(ORGANIZATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Organization.
     * @param value value to set the Organization
     */
    public void setOrganization(String value) {
        setAttributeInternal(ORGANIZATION, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Department, using the alias name Department.
     * @return the Department
     */
    public String getDepartment() {
        return (String)getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Department.
     * @param value value to set the Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for ItemName, using the alias name ItemName.
     * @return the ItemName
     */
    public String getItemName() {
        return (String)getAttributeInternal(ITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemName.
     * @param value value to set the ItemName
     */
    public void setItemName(String value) {
        setAttributeInternal(ITEMNAME, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the Qty
     */
    public Number getQty() {
        return (Number)getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for RespId, using the alias name RespId.
     * @return the RespId
     */
    public Number getRespId() {
        return (Number)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RespId.
     * @param value value to set the RespId
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the UserId
     */
    public Number getUserId() {
        return (Number)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for WarrantyStartDate, using the alias name WarrantyStartDate.
     * @return the WarrantyStartDate
     */
    public Date getWarrantyStartDate() {
        return (Date)getAttributeInternal(WARRANTYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyStartDate.
     * @param value value to set the WarrantyStartDate
     */
    public void setWarrantyStartDate(Date value) {
        setAttributeInternal(WARRANTYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for WarrantyEndDate, using the alias name WarrantyEndDate.
     * @return the WarrantyEndDate
     */
    public Date getWarrantyEndDate() {
        return (Date)getAttributeInternal(WARRANTYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyEndDate.
     * @param value value to set the WarrantyEndDate
     */
    public void setWarrantyEndDate(Date value) {
        setAttributeInternal(WARRANTYENDDATE, value);
    }

    /**
     * Gets the attribute value for WarrantyCard, using the alias name WarrantyCard.
     * @return the WarrantyCard
     */
    public String getWarrantyCard() {
        return (String)getAttributeInternal(WARRANTYCARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyCard.
     * @param value value to set the WarrantyCard
     */
    public void setWarrantyCard(String value) {
        setAttributeInternal(WARRANTYCARD, value);
    }

    /**
     * Gets the attribute value for Invoice, using the alias name Invoice.
     * @return the Invoice
     */
    public String getInvoice() {
        return (String)getAttributeInternal(INVOICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Invoice.
     * @param value value to set the Invoice
     */
    public void setInvoice(String value) {
        setAttributeInternal(INVOICE, value);
    }

    /**
     * Gets the attribute value for PurchaseDate, using the alias name PurchaseDate.
     * @return the PurchaseDate
     */
    public Date getPurchaseDate() {
        return (Date)getAttributeInternal(PURCHASEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchaseDate.
     * @param value value to set the PurchaseDate
     */
    public void setPurchaseDate(Date value) {
        setAttributeInternal(PURCHASEDATE, value);
    }

    /**
     * Gets the attribute value for PurchasePrice, using the alias name PurchasePrice.
     * @return the PurchasePrice
     */
    public Number getPurchasePrice() {
        return (Number)getAttributeInternal(PURCHASEPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchasePrice.
     * @param value value to set the PurchasePrice
     */
    public void setPurchasePrice(Number value) {
        setAttributeInternal(PURCHASEPRICE, value);
    }

    /**
     * Gets the attribute value for SupplierName, using the alias name SupplierName.
     * @return the SupplierName
     */
    public String getSupplierName() {
        return (String)getAttributeInternal(SUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierName.
     * @param value value to set the SupplierName
     */
    public void setSupplierName(String value) {
        setAttributeInternal(SUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for TotalAmount, using the alias name TotalAmount.
     * @return the TotalAmount
     */
    public Number getTotalAmount() {
        return (Number)getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalAmount.
     * @param value value to set the TotalAmount
     */
    public void setTotalAmount(Number value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for BrandName, using the alias name BrandName.
     * @return the BrandName
     */
    public String getBrandName() {
        return (String)getAttributeInternal(BRANDNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrandName.
     * @param value value to set the BrandName
     */
    public void setBrandName(String value) {
        setAttributeInternal(BRANDNAME, value);
    }

    /**
     * Gets the attribute value for WarrantyMonths, using the alias name WarrantyMonths.
     * @return the WarrantyMonths
     */
    public Number getWarrantyMonths() {
        return (Number)getAttributeInternal(WARRANTYMONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyMonths.
     * @param value value to set the WarrantyMonths
     */
    public void setWarrantyMonths(Number value) {
        setAttributeInternal(WARRANTYMONTHS, value);
    }

    /**
     * Gets the attribute value for PrefixItem, using the alias name PrefixItem.
     * @return the PrefixItem
     */
    public String getPrefixItem() {
        return (String)getAttributeInternal(PREFIXITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrefixItem.
     * @param value value to set the PrefixItem
     */
    public void setPrefixItem(String value) {
        setAttributeInternal(PREFIXITEM, value);
    }

    /**
     * Gets the attribute value for FixedAssetTagId, using the alias name FixedAssetTagId.
     * @return the FixedAssetTagId
     */
    public String getFixedAssetTagId() {
        return (String)getAttributeInternal(FIXEDASSETTAGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedAssetTagId.
     * @param value value to set the FixedAssetTagId
     */
    public void setFixedAssetTagId(String value) {
        setAttributeInternal(FIXEDASSETTAGID, value);
    }

    /**
     * Gets the attribute value for Grn, using the alias name Grn.
     * @return the Grn
     */
    public Number getGrn() {
        return (Number)getAttributeInternal(GRN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Grn.
     * @param value value to set the Grn
     */
    public void setGrn(Number value) {
        setAttributeInternal(GRN, value);
    }

    /**
     * Gets the attribute value for Pr, using the alias name Pr.
     * @return the Pr
     */
    public Number getPr() {
        return (Number)getAttributeInternal(PR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pr.
     * @param value value to set the Pr
     */
    public void setPr(Number value) {
        setAttributeInternal(PR, value);
    }

    /**
     * Gets the attribute value for Spo, using the alias name Spo.
     * @return the Spo
     */
    public Number getSpo() {
        return (Number)getAttributeInternal(SPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Spo.
     * @param value value to set the Spo
     */
    public void setSpo(Number value) {
        setAttributeInternal(SPO, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ProductSerialNo, using the alias name ProductSerialNo.
     * @return the ProductSerialNo
     */
    public String getProductSerialNo() {
        return (String)getAttributeInternal(PRODUCTSERIALNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductSerialNo.
     * @param value value to set the ProductSerialNo
     */
    public void setProductSerialNo(String value) {
        setAttributeInternal(PRODUCTSERIALNO, value);
    }

    /**
     * Gets the attribute value for ProductId, using the alias name ProductId.
     * @return the ProductId
     */
    public String getProductId() {
        return (String)getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductId.
     * @param value value to set the ProductId
     */
    public void setProductId(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for GrnDate, using the alias name GrnDate.
     * @return the GrnDate
     */
    public Date getGrnDate() {
        return (Date)getAttributeInternal(GRNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrnDate.
     * @param value value to set the GrnDate
     */
    public void setGrnDate(Date value) {
        setAttributeInternal(GRNDATE, value);
    }

    /**
     * Gets the attribute value for WarrantyId, using the alias name WarrantyId.
     * @return the WarrantyId
     */
    public String getWarrantyId() {
        return (String)getAttributeInternal(WARRANTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyId.
     * @param value value to set the WarrantyId
     */
    public void setWarrantyId(String value) {
        setAttributeInternal(WARRANTYID, value);
    }

    /**
     * Gets the attribute value for Unit, using the alias name Unit.
     * @return the Unit
     */
    public String getUnit() {
        return (String)getAttributeInternal(UNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Unit.
     * @param value value to set the Unit
     */
    public void setUnit(String value) {
        setAttributeInternal(UNIT, value);
    }

    /**
     * Gets the attribute value for BillNo, using the alias name BillNo.
     * @return the BillNo
     */
    public String getBillNo() {
        return (String)getAttributeInternal(BILLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillNo.
     * @param value value to set the BillNo
     */
    public void setBillNo(String value) {
        setAttributeInternal(BILLNO, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for BillDate, using the alias name BillDate.
     * @return the BillDate
     */
    public Date getBillDate() {
        return (Date)getAttributeInternal(BILLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillDate.
     * @param value value to set the BillDate
     */
    public void setBillDate(Date value) {
        setAttributeInternal(BILLDATE, value);
    }

    /**
     * Gets the attribute value for ProductUser, using the alias name ProductUser.
     * @return the ProductUser
     */
    public String getProductUser() {
        return (String)getAttributeInternal(PRODUCTUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductUser.
     * @param value value to set the ProductUser
     */
    public void setProductUser(String value) {
        setAttributeInternal(PRODUCTUSER, value);
    }

    /**
     * Gets the attribute value for WarrantyRemainingDays, using the alias name WarrantyRemainingDays.
     * @return the WarrantyRemainingDays
     */
    public Date getWarrantyRemainingDays() {
        return (Date)getAttributeInternal(WARRANTYREMAININGDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyRemainingDays.
     * @param value value to set the WarrantyRemainingDays
     */
    public void setWarrantyRemainingDays(Date value) {
        setAttributeInternal(WARRANTYREMAININGDAYS, value);
    }

    /**
     * Gets the attribute value for ReplacementDate, using the alias name ReplacementDate.
     * @return the ReplacementDate
     */
    public Date getReplacementDate() {
        return (Date)getAttributeInternal(REPLACEMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReplacementDate.
     * @param value value to set the ReplacementDate
     */
    public void setReplacementDate(Date value) {
        setAttributeInternal(REPLACEMENTDATE, value);
    }

    /**
     * Gets the attribute value for Location, using the alias name Location.
     * @return the Location
     */
    public String getLocation() {
        return (String)getAttributeInternal(LOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Location.
     * @param value value to set the Location
     */
    public void setLocation(String value) {
        setAttributeInternal(LOCATION, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for PoLineId, using the alias name PoLineId.
     * @return the PoLineId
     */
    public Number getPoLineId() {
        return (Number)getAttributeInternal(POLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoLineId.
     * @param value value to set the PoLineId
     */
    public void setPoLineId(Number value) {
        setAttributeInternal(POLINEID, value);
    }

    /**
     * Gets the attribute value for PoHeaderId, using the alias name PoHeaderId.
     * @return the PoHeaderId
     */
    public Number getPoHeaderId() {
        return (Number)getAttributeInternal(POHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoHeaderId.
     * @param value value to set the PoHeaderId
     */
    public void setPoHeaderId(Number value) {
        setAttributeInternal(POHEADERID, value);
    }

    /**
     * Gets the attribute value for WarrantyTag, using the alias name WarrantyTag.
     * @return the WarrantyTag
     */
    public String getWarrantyTag() {
        return (String)getAttributeInternal(WARRANTYTAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyTag.
     * @param value value to set the WarrantyTag
     */
    public void setWarrantyTag(String value) {
        setAttributeInternal(WARRANTYTAG, value);
    }

    /**
     * Gets the attribute value for ProductUserDept, using the alias name ProductUserDept.
     * @return the ProductUserDept
     */
    public String getProductUserDept() {
        return (String)getAttributeInternal(PRODUCTUSERDEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductUserDept.
     * @param value value to set the ProductUserDept
     */
    public void setProductUserDept(String value) {
        setAttributeInternal(PRODUCTUSERDEPT, value);
    }

    /**
     * Gets the attribute value for ProductUserEmpId, using the alias name ProductUserEmpId.
     * @return the ProductUserEmpId
     */
    public Number getProductUserEmpId() {
        return (Number)getAttributeInternal(PRODUCTUSEREMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductUserEmpId.
     * @param value value to set the ProductUserEmpId
     */
    public void setProductUserEmpId(Number value) {
        setAttributeInternal(PRODUCTUSEREMPID, value);
    }

    /**
     * Gets the attribute value for CostCenter, using the alias name CostCenter.
     * @return the CostCenter
     */
    public Number getCostCenter() {
        return (Number)getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostCenter.
     * @param value value to set the CostCenter
     */
    public void setCostCenter(Number value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for CostCenterName, using the alias name CostCenterName.
     * @return the CostCenterName
     */
    public String getCostCenterName() {
        return (String)getAttributeInternal(COSTCENTERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostCenterName.
     * @param value value to set the CostCenterName
     */
    public void setCostCenterName(String value) {
        setAttributeInternal(COSTCENTERNAME, value);
    }

    /**
     * Gets the attribute value for LastMaintainDate, using the alias name LastMaintainDate.
     * @return the LastMaintainDate
     */
    public Date getLastMaintainDate() {
        return (Date)getAttributeInternal(LASTMAINTAINDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastMaintainDate.
     * @param value value to set the LastMaintainDate
     */
    public void setLastMaintainDate(Date value) {
        setAttributeInternal(LASTMAINTAINDATE, value);
    }

    /**
     * Gets the attribute value for MaintainPeriod, using the alias name MaintainPeriod.
     * @return the MaintainPeriod
     */
    public Number getMaintainPeriod() {
        return (Number)getAttributeInternal(MAINTAINPERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaintainPeriod.
     * @param value value to set the MaintainPeriod
     */
    public void setMaintainPeriod(Number value) {
        setAttributeInternal(MAINTAINPERIOD, value);
    }

    /**
     * Gets the attribute value for NextMaintainDate, using the alias name NextMaintainDate.
     * @return the NextMaintainDate
     */
    public Date getNextMaintainDate() {
        return (Date)getAttributeInternal(NEXTMAINTAINDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextMaintainDate.
     * @param value value to set the NextMaintainDate
     */
    public void setNextMaintainDate(Date value) {
        setAttributeInternal(NEXTMAINTAINDATE, value);
    }

    /**
     * Gets the attribute value for ScheduleMaintainFlag, using the alias name ScheduleMaintainFlag.
     * @return the ScheduleMaintainFlag
     */
    public String getScheduleMaintainFlag() {
        return (String)getAttributeInternal(SCHEDULEMAINTAINFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScheduleMaintainFlag.
     * @param value value to set the ScheduleMaintainFlag
     */
    public void setScheduleMaintainFlag(String value) {
        setAttributeInternal(SCHEDULEMAINTAINFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjWarrantyManagementLineEOImpl.
     */
    public MnjWarrantyManagementLineEOImpl getMnjWarrantyManagementLineEO() {
        return (MnjWarrantyManagementLineEOImpl)getAttributeInternal(MNJWARRANTYMANAGEMENTLINEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjWarrantyManagementLineEOImpl.
     */
    public void setMnjWarrantyManagementLineEO(MnjWarrantyManagementLineEOImpl value) {
        setAttributeInternal(MNJWARRANTYMANAGEMENTLINEEO, value);
    }


    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[]{detailId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        /* Sequence Generation Code of Header by PwC */ 
         
         oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_WARRANTY_REPLACE_LINE_S",getDBTransaction());          
         oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
         setDetailId(sVal);
         System.out.println("In Detail Recently Created Detail ID --> " + sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

      /**
       * Add locking logic here.
       */
      //    public void lock() {
      //        super.lock();
      //    }
       public void lock() {
          try {
              super.lock();
          } catch (oracle.jbo.RowInconsistentException e) {
              if (e.getErrorCode().equals("25014")) {
                  super.lock();
              } else
                  throw e;
          }
      }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
