package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 02 14:06:16 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjWarrantyDataLoaderVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjWarrantyDataLoaderVOImpl() {
    }
}
