package model.view;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 02 14:09:10 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjWarrantyManagementHeaderVOExSetParentImpl extends MnjWarrantyManagementHeaderVOImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjWarrantyManagementHeaderVOExSetParentImpl() {
    }
}
