package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 02 22:17:09 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WarrHeaderScheduleHistoryVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WarrHeaderScheduleHistoryVOImpl() {
    }
}
