package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 03 02:23:17 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WarrLineScheduleHistoryVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WarrLineScheduleHistoryVOImpl() {
    }
}
